### ISSUE TITLE
Cannot round corners of Labels

### ISSUE THREAD

**Issue by hrosado20** [Juanpe/SkeletonView#168]
Hi,
I have _labels_ and a _text View_ and I try to use the properties 

> ".linesCornerRadius = 10"

 and 

> ".lastLineFillPercent = 100"

but nothing change.
![IMG_1258](https://user-images.githubusercontent.com/38390139/61007623-e3f9c500-a332-11e9-9e04-6c657e9fa7e2.PNG)

### What did you expect to happen?

Is there any way to have the skeleton of labels and text views like this?
<img width="160" alt="33116319-9d82fa54-cf64-11e7-9eab-3021f6d8d3a2" src="https://user-images.githubusercontent.com/38390139/61007250-f7586080-a331-11e9-9bd4-b90e0d3cd00d.png">

Thanks.

### SkeletonView Environment

**SkeletonView version:** 'https://github.com/Juanpe/SkeletonView.git', :branch => 'feature/Allow_updating_skeleton_layers'
**Xcode version:** 10.2.1
**Swift version:** 4.0

**Comment by ohserezha** [comment]
are you setting `masksToBounds` to `false` for your labels somewhere?

**Comment by Juanpe** [comment]
Hi @hrosado20, please, could you use the last version (1.8)?

**Comment by hashem-intelligentb** [comment]
I have this issue, even by using version 1.8

**Comment by hrool20** [comment]
I've found an answer. You need to declare `.linesCornerRadius` and `lastLineFillPercent` before you call `showAnimatedGradientSkeleton()`.
![Captura de Pantalla 2019-09-05 a la(s) 15 51 48](https://user-images.githubusercontent.com/13945077/64379705-15220900-cff5-11e9-99b6-155e992a69ac.png)

I hope this example I made with a collection view can help you 👍 
[SkeletonExample.zip](https://github.com/Juanpe/SkeletonView/files/3581208/SkeletonExample.zip)

**Comment by gapl** [comment]
Same, I'm also experiencing this issue.

Using version `SkeletonView v1.8.1`

I can confirm the label's layer has `masksToBounds = true` and that I'm setting `linesCornerRadius` and `lastLineFillPercent` before calling `showAnimatedGradientSkeleton()`.

```
label.layer.masksToBounds = true
label.lastLineFillPercent = Int.random(in: 20...70)
label.linesCornerRadius = 5
label.showAnimatedGradientSkeleton(
    usingGradient: SkeletonGradient(baseColor: .powderGrey),
    transition: .crossDissolve(0.2))
```

![IMG_0E2602C894A9-1](https://user-images.githubusercontent.com/16098948/64721196-ceaf2d00-d480-11e9-9396-ade6189e0fca.jpeg)

**Comment by Juanpe** [comment]
Hi all, sorry for the confusing, actually you can do that:
```swift
label.lastLineFillPercent = Int.random(in: 20...70)
label.linesCornerRadius = 5
```

There was a bug related to this :( 

I've released a new version (1.8.2). Please, update your pod and tell me if it's fixed or not. 

Thanks

**Comment by gapl** [comment]
Thanks for the update. I tried it out and it still doesn't work. I'm using labels inside a collection view cell if that makes a difference.

**Comment by gapl** [comment]
Additionally, v1.8.2 introduced a bug in laying out collection view cells with skeleton animations enabled. The cells "animate in" from top left corner of the collection view and they all have the same frame origin. I can provide a recording later, if you're unable to reproduce.

**Comment by d1mster** [comment]
@gapl Same issue. After updating to newer version it still doesn't work.

**Comment by kikikiktai** [comment]
> @gapl Same issue. After updating to newer version it still doesn't work.

+1, @Juanpe are there any stable version that we can downgrade to now? I was coming from 1.6.1 -> 1.8.2, all my skeleton views are broken

**Comment by Juanpe** [comment]
Hi, you can use version 1.8, but...what do you exactly mean when are you saying all your skeleton views are broken? please, could you provide more info about that?
Thanks

**Comment by kikikiktai** [comment]
@Juanpe I was using `UIView.tag` to manually change the height of some UILabels, after updating to 1.8.2 the specific line heights doesn't work anymore, but I saw your comment above saying that specific view's appearance won't work now so it's fine. The main problem now is the corner radius won't work.  I'm also using labels inside a collection view cell. Great library btw :D

**Comment by jordanpichler** [comment]
Rounded corners work for my labels in UICollectionViewCells on 1.8.1 but are broken on 1.8.2 for me. 

But yes, this is truly a great library! Thanks! ✨

**Comment by Juanpe** [comment]
Hi all, this problem has been fixed in version 1.8.4 :)
