### ISSUE TITLE
Gradient Animation not working when app becomes active

### ISSUE THREAD

**Issue by attheodo** [Juanpe/SkeletonView#39]
When the app goes in the background and comes back as active, the gradient animation on Skeleton View is not working.

**Comment by Juanpe** [comment]
Hi @attheodo, this issue has been solved in [version 1.1](https://github.com/Juanpe/SkeletonView/releases/tag/1.1)

**Comment by attheodo** [comment]
@Juanpe just updated to `1.1`. It doesn't seem like the issue has been properly fixed.

**Comment by Juanpe** [comment]
Hi @attheodo, you're right. Today, I'm going to release an hotfix to solve this problem 🙃 [commit](https://github.com/Juanpe/SkeletonView/commit/e89de65a2b3eb8abbc32f3d606d229fa9d08dea0)

**Comment by Juanpe** [comment]
Hi @attheodo, I've released a new version (1.1.1), now it should work fine 🙂

**Comment by attheodo** [comment]
@Juanpe nope, it doesn't 😅

**Comment by Juanpe** [comment]
Sorry man, I re uploaded the version 1.1.1, could you update your pods?

**Comment by attheodo** [comment]
@Juanpe still same issue buddy. Did you update `1.1.1` in the trunk?

**Comment by Juanpe** [comment]
Hi @attheodo, new version is out ```1.2```, should solve this issue

**Comment by Dalein** [comment]
I'm using 1.4.1 ver and still see this bug. It's very simple to reproduce:
Start skeleton animation:

` let gradient = SkeletonGradient(baseColor: UIColor.nephritis)
        let animation = SkeletonAnimationBuilder().makeSlidingAnimation(withDirection: .leftRight)
        self.showAnimatedGradientSkeleton(usingGradient: gradient, animation: animation)`

**Comment by pendikov** [comment]
@Dalein me too

**Comment by GaneshKumarSelvam** [comment]
@Juanpe is this issue solved, I see the same issue in 1.8.1, when I go to background and come it shows like frozen

<img width="350" alt="Screen Shot 2019-09-10 at 2 41 02 PM" src="https://user-images.githubusercontent.com/22673703/64600592-0f536b80-d3d9-11e9-97be-f0e67ec70c7d.png">

**Comment by cwestMobile** [comment]
I am also experiencing this issue

**Comment by i0sa** [comment]
this needs to be fixed

**Comment by Juanpe** [comment]
Hi @i0sa, could you install a specific branch? next version should fix this problem.
```
pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git', :branch => 'master'
```
